### PR TITLE
Devcontainer rust analyzer

### PR DESCRIPTION
**Pull request by nshaaban-cPacket**
Switched to rust-analyzer per recommendation [here](https://github.com/1c3t3a/rust-socketio/pull/50#discussion_r669493106). Looks like autocomplete is working now (perhaps I didn't wait long enough before? rust-anaylzer's start up time is significantly greater than rls). Also found (and mentioned in a comment) the settings in rust-analyzer to make it less noisy.

### CODE REVIEW

**Review by 1c3t3a — APPROVED** [review]
Nice, that looks good.

**Comment by 1c3t3a** [comment]
Should this target `main`?

**Comment by nshaaban-cPacket** [comment]
> Should this target `main`?

I'd prefer it on refactoring, rebasing refactoring from main is a headache I'd rather avoid (lots of clicking accept incoming changes). We're far enough into the refactoring process that any functional PR will need to target refactoring (or re-written) to prevent major git merge conflicts. It will be on main when refactoring is merged.

**Comment by 1c3t3a** [comment]
Sounds reasonable!

**Pull request merged**
