### PR TITLE
comments

### PR DESCRIPTION
**Pull request by kw-fn**
got back to reading the comments again and saw
some places where the wording might be improved

:pizza:

### CODE REVIEW

**Comment by 1c3t3a** [comment]
Ah nice, that's helpful. But I think we should wait for the other PRs (Containerized tests and sync version) to get merge, in order to keep the commit history clean.

**Comment by kw-fn** [comment]
I think I reset those PRs in my fork for this branch so this should merge into
the existing code as is or am I missing something?

**Comment by kw-fn** [comment]
only conflict I think is that this should be merged ahead of the documentation
changes in the PR removing async code

**Comment by kw-fn** [comment]
as well I made sure to `cargo fmt` this for the linter but it's not passing, are there other
changes I need to make in my branch?

**Comment by 1c3t3a** [comment]
> the only conflict I think is that this should be merged ahead of the documentation
> changes in the PR removing async code

Ahhh sorry I've missed that. Let's see if it is possible to resolve the conflicts and get this through.

**Comment by 1c3t3a** [comment]
I merged the points by hand, I don't see any other changes affecting the code, so after your review of my latest commit we are ready to merge!

**Comment by kw-fn** [comment]
great, though I could have more clearly cross-referenced the PRs for you

**Comment by 1c3t3a** [comment]
> great, though I could have more clearly cross-referenced the PRs for you

No worries! The checks should pass now, could you please rebase and add a descriptive commit message (conventional commit standard)?

**Comment by 1c3t3a** [comment]
Ah did you rebase on your main branch? I actually meant the upstream main branch ;) And could you maybe also squash your commits (through `rebase --interactive)`? Sorry I forgot to mention this, but in that way we keep the history cleaner.

**Comment by kw-fn** [comment]
this is rebased to upstream main yes

**Comment by kw-fn** [comment]
this is more difficult for me since I'm on the branch of a fork I think merging directly into upstream
would be simpler if you wanted to squash the commits

**Comment by 1c3t3a** [comment]
> this is more difficult for me since I'm on the branch of a fork I think merging directly into upstream/main
> would be simpler if you wanted to squash the commits

Ahh I see, then I try to squash the commits before merging. Anyways I now see a deletion of `CONTRIBUTING.md` in the changed files, I assume this was not intended?

**Comment by kw-fn** [comment]
those changes weren't part of the merge and I don't recall seeing that in the
commit, I think it would be best to take handful of the merged files from `src`
and push directly to `main` if you can I tried this but I cannot, otherwise I
would start a clean branch and do the same, maybe something went wrong when I
started the branch and reverted the contents of then existing PRs which have
since been merged, either way the commit log is a mess and I would be stabbing
in the dark to get the commits properly squashed

**Comment by 1c3t3a** [comment]
Alright this was a hard piece of git hacking, but I got it working now. Could you review the changes if they are the ones you've committed, afterwards we could merge!

**Comment by kw-fn** [comment]
yeah this is everything, thanks for untangling that mess, do you use a GUI or just the CLI?

**Comment by 1c3t3a** [comment]
Sure no problem! I was using the CLI and untangled this with `git rebase --interactive` ;)

**Review by 1c3t3a — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
