### PR TITLE
feat: TransportTypes

### PR DESCRIPTION
**Pull request by nshaaban-cPacket**
Trait objects are a royal pain to deal with.

### CODE REVIEW

**Comment by 1c3t3a** [comment]
Mh I could understand that. Am I right that you plan on removing them completely?

**Comment by nshaaban-cPacket** [comment]
> Mh I could understand that. Am I right that you plan on removing them completely?

When reasonable. There are times when trait objects can be really nice, however in this instance since the list of implementations is fixed an enum works much cleaner. It is difficult (if not impossible) to get trait objects Clonable, Sized, and usable.

**Comment by 1c3t3a** [comment]
> > Mh I could understand that. Am I right that you plan on removing them completely?
> 
> When reasonable. There are times when trait objects can be really nice, however in this instance since the list of implementations is fixed an enum works much cleaner. It is difficult (if not impossible) to get trait objects Clonable, Sized, and usable.

Alright, understand that, then lets keep it for now!

**Comment by 1c3t3a** [comment]
Could you resolve the conflicts? Then we're ready to merge!

**Pull request merged**
