### PR TITLE
docker ci/cd files - oliver

### PR DESCRIPTION
**Pull request by kw-fn**
files to start adding a ci/cd test suite to GH Actions

### CODE REVIEW

**Comment by kw-fn** [comment]
is this the same build failure as last time? I don't think any compiled code is being touched here

**Comment by 1c3t3a** [comment]
Hey the CI pipeline looks great so far! Thank you. The lint is kind of strange, it's apparently the clippy lints that are firing, I wonder why this happened just now.

**Comment by 1c3t3a** [comment]
I think the issue was just bad formatting in the push.yml file. Wonder why GitHub doesn't spit out error messages in such situations.

**Comment by kw-fn** [comment]
it appears that the node server is running but the `cargo test` instruction
isn't finishing by closing that process

**Comment by kw-fn** [comment]
I think the workflow is activating it looks to me like a
problem with the Docker container initializing

**Comment by 1c3t3a** [comment]
I think we could rebase here onto `upstream/master` in order to test against the latest version.

**Comment by 1c3t3a** [comment]
Oke this issue seems to come from `docker buildx`, it's working locally for me and my docker compose version is: `docker-compose version 1.27.4, build 40524192`.

**Comment by 1c3t3a** [comment]
Alright thats progress! I think the only tests that are failing now are the ones concerning the engine.io protocol. In the current version those are trying to connect to a server on port 4200. We should add that server to the docker-compose file as well ;)

**Comment by kw-fn** [comment]
I've been thinking about this project and it might have been, or still be, more convenient for me to set-up a CI task in the fork and iteratively test on that.

**Comment by kw-fn** [comment]
Actually I just looked closer and I think the versioning updates and the removal of the buildx is working it's just the tests that aren't passing which is a separate issue. If you wouldn't mind merging this I can reset my fork and start looking at other areas of the projects.

**Comment by kw-fn** [comment]
Haha I tried squashing this again but it's just as confusing as before. Is there some reason not all of the commit history would be showing? Anyway I would simply close this a rebase the few changed files to a 'clean' PR unless you have the inclination to untangle another commit log.

**Comment by 1c3t3a** [comment]
> Haha I tried squashing this again but it's just as confusing as before. Is there some reason not all of the commit history would be showing? Anyway I would simply close this a rebase the few changed files to a 'clean' PR unless you have the inclination to untangle another commit log.

Haha yeah I think the reset makes sense, there's a lot of confusion in the history ;) Otherwise I'll squash all commits to one when merging. But before merging it I would like to see the checks green, which can't happen without a running engine.io instance in docker-compose. For a first version it would make sense to execute just the tests related to socket.io via: `cargo test --verbose --lib -- socketio::transport::test test::it_works`.

**Comment by kw-fn** [comment]
closing so I can test CI/CD on the fork

**Comment by kw-fn** [comment]
What do you think about replicating the entire package in the docker and testing there?

**Comment by 1c3t3a** [comment]
What do you mean by replicating? I would say we have to replicate the socket.io container and just start the engine.io Client in there.

**Comment by kw-fn** [comment]
I meant copying all of rust-socketio into a Docker container and including cargo and running everything inside of that. I'm not certain Docker is capable of exposing the Node servers in the way we need within CI/CD. Mostly since I haven't seen any examples showing this.

**Comment by 1c3t3a** [comment]
Ah I see what you mean. It would make sense IMO, you could maybe just take a plain Ubuntu or alpine image and install all dependencies there!

**Comment by kw-fn** [comment]
This seems like progress so far

**Pull request closed without merging**
