### PR TITLE
Implemented a response to the server after the client received the message.

### PR DESCRIPTION
**Pull request by mars1211**
Implemented the functionality from my question: https://github.com/1c3t3a/rust-socketio/issues/292

### CODE REVIEW

**Comment by 1c3t3a** [comment]
Hi @mars1211, can you please rebase your change, fix the merge conflicts and squash all changes to one commit? Thank you :)

**Comment by 1c3t3a** [comment]
Friendly ping

**Comment by shenjackyuanjie** [comment]
Friendly ping +1(

**Comment by shenjackyuanjie** [comment]
@1c3t3a little question, did #384 solve this pr?

**Pull request closed without merging**
